baseurl = "https://oclworkshop.github.io/2021/"
languageCode = "en-en"
title = "OCL Workshop"
theme = "slender"
disableRSS = true
disableSitemap = true
#log = true
#logFile = "log.txt"
#verbose = true
uglyURLs = true
#verboseLog = true

[params]
  colorscheme = "teal"
  description = "20th International Workshop on OCL and Textual Modeling"

  # Tagline; HTML accepted here. Keep it concise.
  tagline = "20th International Workshop on OCL and Textual Modeling, June 25 2021, Bergen, Norway"

  # Footer; Markdown accepted here.
  footer = "Copyright 2021 &copy; OCL Workshop 2021 Organizers | Powered by [Hugo](http://gohugo.io) and the [Slender](http://themes.gohugo.io/slender/) theme"

  # Description and keywords for <meta> tags.
  # Remember to set this for your main page.
  # This will be overridden by whatever is set by the page or post,
  # defined by `description` and `keywords` variables in the front matter
  # of the markdown file.
   keywords = "OCL Workshop, STAF 2021, STAF'2021, textual modelling, UML/OCL"

  # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
  # Remove, comment, or leave blank any field to leave them out.
   email = "mailto:ocl2021@easychair.org"
   github = "https://github.com/oclworkshop"
   twitter = "https://twitter.com/oclworkshop"
   linkedin = "https://www.linkedin.com/groups/3007822"
